export const wpEndpoints = {
  auth: {
    login: '/jwt-auth/v1/token',
    validate: '/jwt-auth/v1/token/validate',
    me: '/trenerka/v1/auth/me',
    registerTrainer: '/trenerka/v1/auth/register-trainer',
    resendVerification: '/trenerka/v1/auth/resend-verification',
    registerClient: '/trenerka/v1/auth/register-client',
    resetPassword: '/trenerka/v1/auth/reset-password',
    trainerProfile: '/trenerka/v1/trainer/profile',
  },
  clients: '/trenerka/v1/clients',
  invites: '/trenerka/v1/invites',
  invitesValidate: '/trenerka/v1/invites/validate',
  clientAttachments: (clientId: string) => `/trenerka/v1/clients/${clientId}/attachments`,
  clientAttachment: (clientId: string, attachmentId: string) =>
    `/trenerka/v1/clients/${clientId}/attachments/${attachmentId}`,
  exercises: '/trenerka/v1/exercises',
  programs: '/trenerka/v1/programs',
  clientPrograms: '/trenerka/v1/client-programs',
  clientProgress: (clientId: string) => `/trenerka/v1/clients/${clientId}/progress`,
  events: '/trenerka/v1/events',
  payments: '/trenerka/v1/payments',
  paymentReports: '/trenerka/v1/payments/reports',
  messages: '/trenerka/v1/messages',
  messageUnreadCounts: '/trenerka/v1/messages/unread-counts',
  notifications: '/trenerka/v1/notifications',
  upload: '/trenerka/v1/upload',
  client: {
    dashboard: '/trenerka/v1/client/dashboard',
    workouts: '/trenerka/v1/client/workouts',
    progress: '/trenerka/v1/client/progress',
    profile: '/trenerka/v1/client/profile',
    attachments: '/trenerka/v1/client/attachments',
  },
  analytics: {
    trainer: '/trenerka/v1/analytics/trainer',
    attendance: '/trenerka/v1/analytics/attendance',
    weekday: '/trenerka/v1/analytics/weekday',
    retention: '/trenerka/v1/analytics/retention',
    subscriptions: '/trenerka/v1/analytics/subscriptions',
    clientPdf: (id: string) => `/trenerka/v1/analytics/client/${id}/pdf`,
    summaryExport: '/trenerka/v1/analytics/summary-export',
  },
  clientWorkoutCompletions: (clientId: string) => `/trenerka/v1/clients/${clientId}/workout-completions`,
  admin: {
    stats: '/trenerka/v1/admin/stats',
    users: '/trenerka/v1/admin/users',
    user: (id: string) => `/trenerka/v1/admin/users/${id}`,
    platformPlans: '/trenerka/v1/admin/platform-plans',
  },
  news: '/trenerka/v1/news',
  posts: {
    exercises: '/wp/v2/trenerka_exercise',
    clients: '/wp/v2/trenerka_client',
    programs: '/wp/v2/trenerka_program',
    events: '/wp/v2/trenerka_event',
    payments: '/wp/v2/trenerka_payment',
    messages: '/wp/v2/trenerka_message',
  },
} as const
